name: Publish Nuget Package

on:
  workflow_run:
    workflows: [ Update Version ]
    types:
      - completed

defaults:
  run:
    shell: |
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
env:
  BUILD_CONFIGURATION:  'Release'

jobs:
  build:
    runs-on: windows-latest
    if:       ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Pack
        run:  |
              dotnet pack -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'
    
      - name: Upload Package to nuget.org
        uses: tedd/publish-nuget-neo@v1.0.2
        with:
          NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
